services:
  - type: web
    name: web-platform-for-online-product
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      pip install -r backend/requirements.txt
    startCommand: cd backend && python run.py