services:
  - type: web
    name: web-platform-for-online-product   # ต้องตรงกับชื่อใน Render
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r backend/requirements.txt
    startCommand: cd backend && python run.py