services:
  - type: web
    name: web-platform-for-online-product
    env: python
    plan: free

    buildCommand: |
      pip install -r backend/requirements.txt
      playwright install chromium

    startCommand: cd backend && python run.py